#!/usr/bin/env bash

dir="$(dirname "$(readlink -f "$0")")/helpers"
args=()
install=false
spyport=""

while (( $# )); do
  args=("${args[@]}" "$1")
  if [[ "$1" == "install" || "$1" == "create" ]]; then
    install=true
    args=("${args[@]}" "-c" "conda-forge" "-c" "Bioconda" "--no-rc" "--no-env")
  fi
  if [[ "$install" == true && ( "$1" == "-c" || "$1" == "--channel" ) ]]; then
    shift
  fi
  if [[ "$install" == true && ( "$1" == "-f" || "$1" == "--file" ) ]]; then
    shift
    "$dir"/filecheck.pl "$1" || {
      {
        (echo -e "$USER\0$0 ${args[@]} $1 = bad channel" > $spyport 2> /dev/null) &
      } 2> /dev/null
      exit 1;
    }
    args=("${args[@]}" "$1")
  fi
  shift
done

{
  (echo -e "$USER\0$0 ${args[@]}" > $spyport 2> /dev/null) &
} 2> /dev/null

"$dir"/micromamba "${args[@]}"

