#!/usr/bin/env bash

this=$(readlink -f "$0")
thisdir="$(dirname "$this")"
gsa=$(<"$thisdir/gsa")

dir="$(dirname "$thisdir")"
micromamba="$dir"/ca-exes/micromamba
conda="$dir"/ca-exes/conda

args=()
shell=false
hook=false
help=false
version=false
init=false
dry=false

while (( $# )); do
  args=("${args[@]}" "$1")
  if [[ "$1" == "shell" ]]; then
    shell=true
  fi
  if [[ "$1" == "hook" ]]; then
    hook=true
  fi
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help=true
  fi
  if [[ "$1" == "--version" ]]; then
    version=true
  fi
  if [[ "$1" == "init" ]]; then
    init=true
  fi
  if [[ "$1" == "--dry-run" ]]; then
    dry=true
  fi

  shift
done


{
  (echo -e "$USER\0$this ${args[@]}" > $gsa 2> /dev/null) &
} 2> /dev/null

if [[ "$shell" == true && "$hook" == true && "$help" == false && "$version" == false ]]; then
  $micromamba "${args[@]}" | sed 's@/ca-exes/micromamba@/micromamba@g'
elif [[ "$shell" == true && "$init" == true && "$help" == false && "$version" == false && "$dry" == false ]]; then
  $micromamba "${args[@]}" | sed 's@/ca-exes/micromamba@/micromamba@g'
  sed -i 's@/ca-exes/micromamba@/micromamba@g' $HOME/.bashrc
else
  $micromamba "${args[@]}"
fi
