#!/usr/bin/env bash

faux=$(basename -- "$0")
this=$(readlink -f "$0")
thisdir="$(dirname "$this")"
gsa=$(<"$thisdir/gsa")

rdir="$(dirname "$thisdir")"
real="$rdir"/ca-exes/$faux

args=()
shell=false
hook=false
help=false
init=false
dry=false
verbose=false
activate=false

while (( $# )); do
  args=("${args[@]}" "$1")
  if [[ "$1" == "shell" || "$1" == "shell.bash" || "$1" == "shell.posix" ]]; then
    shell=true
  fi
  if [[ "$1" == "hook" ]]; then
    hook=true
  fi
  if [[ "$1" == "activate" || "$1" == "reactivate" ]]; then
    activate=true
  fi
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help=true
  fi
  if [[ "$1" == "init" ]]; then
    init=true
  fi
  if [[ "$1" == "-d" || "$1" == "--dry-run" ]]; then
    dry=true
  fi
  if [[ "$1" == "-v" || "$1" == "--verbose" ]]; then
    verbose=true
  fi

  shift
done

{
  (echo -e "$USER\0$this($faux) ${args[@]}" > $gsa 2> /dev/null) &
} 2> /dev/null

if [[ "$shell" == true && "$hook" == true && "$help" == false ]]; then
  echo "export CONDA_GROUP="$(id -gn $USER) && $real "${args[@]}" | sed 's@/ca-exes/miniconda/bin/conda@/conda@g'
elif [[ "$shell" == true && "$activate" == true && "$help" == false ]]; then
  echo "export CONDA_GROUP="$(id -gn $USER) && echo "export CONDA_EXE=$rdir/conda" && $real "${args[@]}" | sed 's@/ca-exes/miniconda/bin/conda'\''@/conda'\''@g' | sed 's@export PATH='\'$rdir'/ca-exes/miniconda/bin:@export PATH='\'$rdir':'$rdir'/ca-exes/miniconda/bin:@g'
elif [[ "$init" == true && "$help" == false ]]; then
  if [[ "$verbose" == true ]]; then
    $real "${args[@]}" | sed 's@/ca-exes/miniconda/bin/conda@/conda@g'
  fi
  if [[ "$dry" == false ]]; then
    if [[ "$verbose" == false ]]; then
      $real "${args[@]}"
    fi
    sed -i 's@ca-exes/miniconda/bin\(/\)\{0,1\}@@g' $HOME/.bashrc
  fi
else
  $real "${args[@]}"
fi
